

services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: coursedb
      MYSQL_ROOT_PASSWORD: 'Thao123'
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env

  django-web:
    build: .
    container_name: django-docker
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - ./temp_dir:/app/temp_dir
      - gunicorn_socket:/app/gunicorn_socket
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  celery-worker:
    build: .
    container_name: celery-worker
    command: celery -A courseapp worker --loglevel=info
    depends_on:
      - redis
      - django-web
    env_file:
      - .env
    volumes:
      - ./temp_dir:/app/temp_dir

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - gunicorn_socket:/app/gunicorn_socket
    ports:
      - "80:80"
    depends_on:
      - django-web

volumes:
  mysql_data:
  gunicorn_socket:
