# Generated by Django 5.0.8 on 2025-04-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
