# Generated by Django 5.0.8 on 2025-04-22 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_lesson_course_alter_payment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='timestamp',
            field=models.PositiveIntegerField(),
        ),
    ]
