# Generated by Django 5.0.8 on 2025-05-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_emailotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
